const userConstants = {
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    GETME_REQUEST: 'USERS_GETME_REQUEST',
    GETME_SUCCESS: 'USERS_GETME_SUCCESS',
    GETME_FAILURE: 'USERS_GETME_FAILURE',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',
    REGISTER_RESET: 'USERS_REGISTER_RESET',

    DELETE_USER_REQUEST: 'USERS_DELETE_USER_REQUEST',
    DELETE_USER_SUCCESS: 'USERS_DELETE_USER_SUCCESS',
    DELETE_USER_FAILURE: 'USERS_DELETE_USER_FAILURE',
    RESET: 'USERS_RESET'
};
export default userConstants;